[project]
name = "yolodex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "openai>=2.17.0",
    "pillow>=11.3.0",
    "ultralytics>=8.4.12",
    "yt-dlp>=2025.10.14",
]
